### ISSUE TITLE
Need more information on how to use transpile module to include a complete module. 

### ISSUE THREAD

**Issue by amitsingh-quotient** [martpie/monorepo-typescript-next-the-sane-way#21]
I tried this similar approach used here to integrate module from react JS to next JS. I am successfully able to do so. But i get few build error. 

I am actually transpiling the whole package in my next JS. which works fine. But i am getting this error. Can you help me. 

This is where i import shopping list from another project using npm link. and use transpile-module to resolve all dependencies.

<img width="736" alt="Screenshot 2021-05-13 at 8 51 01 PM" src="https://user-images.githubusercontent.com/57741695/118147277-09732080-b42d-11eb-924d-e3d351501413.png">

Error in next JS after the import. 

<img width="1440" alt="Screenshot 2021-05-13 at 8 49 28 PM" src="https://user-images.githubusercontent.com/57741695/118147228-00824f00-b42d-11eb-9068-0d4ab1963cd4.png">

This is package file of shopping-list module. 

<img width="534" alt="Screenshot 2021-05-13 at 8 50 03 PM" src="https://user-images.githubusercontent.com/57741695/118147260-06783000-b42d-11eb-919d-5331ea06f622.png">

This is index.js which is imported as shopping-list.

<img width="534" alt="Screenshot 2021-05-13 at 8 50 20 PM" src="https://user-images.githubusercontent.com/57741695/118147271-08da8a00-b42d-11eb-8dd4-045ed5366563.png">

**Comment by martpie** [comment]
Sorry I just saw your issue now, did you manage to fix your issue?
