### ISSUE TITLE
Recompiling after every page request

### ISSUE THREAD

**Issue by AlenPelin** [martpie/monorepo-typescript-next-the-sane-way#4]
This one is related to closed #2. In a nutshell, running `npm run dev` on Windows it keeps recompiling app over and over - without any file modifications. @martpie have you seen this before? Is it expected? 

It shows following file is getting changed:
```
website\.next\react-loadable-manifest.json
```

**Comment by martpie** [comment]
Yep, I know why, I'll submit a fix soon.

**Comment by martpie** [comment]
Shoud be better after 338155a722abb2e813b497a41f2a90441d4a0644
